### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by aibow** [WeBankFinTech/fes.js#1]
npm install @webank/wnpm -g --registry=http://wnpm.weoa.com:8001

npm ERR! code ETIMEDOUT
npm ERR! errno ETIMEDOUT
npm ERR! network request to http://wnpm.weoa.com:8001/@webank%2fwnpm failed, reason: connect ETIMEDOUT 69.172.201.153:8001
npm ERR! network This is a problem related to network connectivity.

**Comment by wanchun** [comment]
The document has been updated.

> npm install @ webank / wnpm -g --registry = http://wnpm.weoa.com:8001
> 
> npm ERR！代码ETIMEDOUT
> npm ERR！errno ETIMEDOUT
> npm ERR！到[http://wnpm.weoa.com:8001/@webank%2fwnpm的](http://wnpm.weoa.com:8001/@webank%2fwnpm)网络请求失败，原因：连接ETIMEDOUT 69.172.201.153:8001
> npm ERR！网络这是与网络连接有关的问题。
