### ISSUE TITLE
CORS 跨域请求的问题

### ISSUE THREAD

**Issue by textproofreading** [WeBankFinTech/fes.js#10]
碰到了一个CORS 跨域请求的问题

我的环境：
    1）本地运行 fes dev
    2）本地另一个端口运行api 接口服务

碰到跨域的问题：

1） 跨域访问，根据协议要求，会先发出 OPTIONS 请求
    
    比如访问：
    XHR OPTIONS http://localhost:9000/api/v1/search/cms/keywords/add

2）如果服务器没有处理 OPTIONS 请求：
    会出现以下错误：

    [HTTP/1.1 404 Not Found 1ms]
    Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:9000/api/v1/search/cms/keywords/add. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).
    Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:9000/api/v1/search/cms/keywords/add. (Reason: CORS request did not succeed).

3）如果服务器处理了 OPTIONS 请求：
    
即：OPTIONS 中添加：
    
    Header().Set("Access-Control-Allow-Origin", "*")

会出现以下错误：

    Cross-Origin Request Blocked: 
    The Same Origin Policy disallows reading the remote resource at ‘http://localhost:9000/api/v1/search/cms/keywords/add’. 
    (Reason: Credential is not supported if the CORS header ‘Access-Control-Allow-Origin’ is ‘*’).

    Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:9000/api/v1/search/cms/keywords/add. 
    (Reason: CORS request did not succeed).

4）为什么访问 localhost:9000 仍然有跨域的问题呢？

5）我参考了 MDN 的信息：
    To correct this problem on the client side, simply ensure that the credentials flag's value is false when issuing your CORS request.

来源：
https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSNotSupportingCredentials

是不是应该修改 FesApi 的相关代码？

我的问题：CORS 跨域问题应该如何设置？

**Comment by Genuifx** [comment]
本地开发的话可以起服务设置header Access-Control-Allow-Origin: *

**Comment by textproofreading** [comment]
我在 OPTIONS 请求中配置了：Access-Control-Allow-Origin: *

但是提示：
    (Reason: Credential is not supported if the CORS header ‘Access-Control-Allow-Origin’ is ‘*’).


Credential is not supported ，不支持！

**Comment by wanchun** [comment]
貌似Access-Control-Allow-Origin不支持配置 * ，配置下127.0.0.1:5000 ？
另外在mock.js中设置代理可以解决问题
```
cgiMock.proxy('http://127.0.0.1:9000')
```

**Comment by textproofreading** [comment]
1） Access-Control-Allow-Origin 设置了： *  ， 127.0.0.1:5000  都不行
2）在mock.js中设置代理                                    ， 也不行

在访问的时候，在  firefox 浏览器查看  web console  ，发现
1） OPITONS 请求正常

2） post 请求被 block 了， Transferred 状态为： Blocked 。

**Comment by textproofreading** [comment]
我感觉，还是应该修改： FesApi ，

我单独写了一个纯 js 的 XMLHttpRequest 的脚本，可以测试通过，脚本如下：

`    <script >
  var xhr = new XMLHttpRequest();
  xhr.open("post", "http://localhost:9000/api/v1/search/cms/keywords/add", true);
  xhr.setRequestHeader('Content-Type', 'application/json; charset=UTF-8');
 var data_json = {
      a:"b",
      c:"d"
  }
  xhr.send(JSON.stringify(data_json));
  xhr.onloadend = function () {
    // done
  };
</script>
`

**Comment by Genuifx** [comment]
要在客户端改正这个问题，只需要确保发出 CORS 请求时将credential设置为false。

如果使用 XMLHttpRequest 发出请求，确保未将 withCredentials 设置为 true。
如果使用 Server-sent events, 确保 EventSource.withCredentials 的值为 false (false为默认值)。
如果使用 Fetch API，确保 Request.credentials 的值为 "omit".
如果还不成功，则需要修改服务端，可能需要修改 Access-Control-Allow-Origin 的值，来为客户端所能够加载资源的源予以授权。


[文档](https://developer.mozilla.org/zh-CN/docs/Web/HTTP/CORS/Errors/CORSNotSupportingCredentials)

**Comment by wanchun** [comment]
> 1） Access-Control-Allow-Origin 设置了： * ， 127.0.0.1:5000 都不行
> 2）在mock.js中设置代理 ， 也不行
> 
> 在访问的时候，在 firefox 浏览器查看 web console ，发现
> 1） OPITONS 请求正常
> 
> 2） post 请求被 block 了， Transferred 状态为： Blocked 。

FesApi默认设置withCredentials为true，跨域请求时携带cookie。

mock跨域配置：
![image](https://user-images.githubusercontent.com/4636302/92248531-6c560480-eefb-11ea-9485-e90bbecc070d.png)
![image](https://user-images.githubusercontent.com/4636302/92248555-77a93000-eefb-11ea-8f1e-634dfc30e4a8.png)
结果：
![image](https://user-images.githubusercontent.com/4636302/92248629-927ba480-eefb-11ea-92a8-07ba1b2e41e0.png)

**Comment by textproofreading** [comment]
感谢各位花费时间解答。
上面的问题已经解决了。
