### ISSUE TITLE
希望框架本身可支持jsx

### ISSUE THREAD

**Issue by hdbaiyu** [WeBankFinTech/fes.js#102]
**您的Feature Request/想法是否与已有问题有关? 请描述。**

多向支持，不单是模板

**简述你想要的解决方案**

希望框架本身可支持jsx

**描述你考虑过的替代方案**
是否有替代方案、你看过的不错的参考方案、交互方案等

**其它补充内容**
任何和这个问题有关的额外内容

**Comment by wanchun** [comment]
“多向支持，不单是模板 ”，啥意思呢？

**Comment by hdbaiyu** [comment]
希望可以支持 jsx 语法

**Comment by wanchun** [comment]
首先说明：vue3版本支持 jsx 语法 

fes.js 给文件路由组件定义了 `<config>` ，模板天然支持，而jsx则需要提供API的方式，目前还没定下API，所以还未支持路由文件用`jsx`。

但是其他组件用jsx是没问题的。
