### ISSUE TITLE
[Bug Report/Feeback]

### ISSUE THREAD

**Issue by NexZhu** [WeBankFinTech/fes.js#107]
`fes build` 行为和文档不一致，并不会生成`.fes`目录

![image](https://user-images.githubusercontent.com/4370605/158938671-a9126a17-2f7b-4a90-a50c-d5a5c36e551e.png)

以下转自微信群：

@qlin 提一个建议：能不能CLI单独加一个生成.fes目录的命令，目前只有npm run dev会生成.fes目录，文档中写npm run build也会生成但实际上不会，而是会生成一个.fes-production目录，build完成后删除。

目前对于CI上跑linting不太友好，typescript-eslint需要.fes目录生成，否则会代码缺失import找不到会报错，用npm run dev生成.fes又不知道什么时候应该停止。

最好能有单独的类似fes gen之类的命令，生成.fes目录，或者让build也生成fes目录（和文档一致）

**Comment by wanchun** [comment]
默认会在构建后清除 `.fes` ，不过如果设置环境变量 `RM_TMPDIR=none`，则不会：
```shell
RM_TMPDIR=none fes build
```

**Comment by NexZhu** [comment]
> 默认会在构建后清除 `.fes` ，不过如果设置环境变量 `RM_TMPDIR=none`，则不会：
> 
> ```shell
> RM_TMPDIR=none fes build
> ```

验证了一下加上`RM_TMPDIR=none`之后留下了`.fes-production`目录，我的CI场景问题能解决，需要执行完之后`cp -r .fes-production .fes`再跑`npm run lint`才能成功，因为TypeScript的shim里面import路径是`.fes`而不是`.fes-production`。

不过仍然和上面文档不一致，可以考虑调整文档说明一下，另外加上这个环境变量说明。

**Comment by wanchun** [comment]
> > 默认会在构建后清除 `.fes` ，不过如果设置环境变量 `RM_TMPDIR=none`，则不会：
> > ```shell
> > RM_TMPDIR=none fes build
> > ```
> 
> 验证了一下加上`RM_TMPDIR=none`之后留下了`.fes-production`目录，我的CI场景问题能解决，需要执行完之后`cp -r .fes-production .fes`再跑`npm run lint`才能成功，因为TypeScript的shim里面import路径是`.fes`而不是`.fes-production`。
> 
> 不过仍然和上面文档不一致，可以考虑调整文档说明一下，另外加上这个环境变量说明。

在 `tsconfig.json` 添加如下配置试试:
```
"paths": {
      "@/*": ["./src/*"],
      "@@/*": ["./src/.fes/*", "./src/.fes-production/*"]
 }
 ```
