### ISSUE TITLE
layout 配置

### ISSUE THREAD

**Issue by lingTing8** [WeBankFinTech/fes.js#115]
**您的Feature Request/想法是否与已有问题有关? 请描述。**
由于我们的项目要部署在不同的环境中

**简述你想要的解决方案**
build一次Docker镜像，多个环境部署，如果不支持运行中配置就要build一个版本镜像，
希望可以在运行中配置侧边的title、log以及主题颜色等

**描述你考虑过的替代方案**
是否有替代方案、你看过的不错的参考方案、交互方案等

**其它补充内容**
任何和这个问题有关的额外内容

**Comment by lingTing8** [comment]
关于loyout配置问题

**Comment by wanchun** [comment]
fes-design组件库使用css变量实现的主题，完全可以运行时动态配置，参考官网配置即可。其他参数我准备支持运行时配置。
