### ISSUE TITLE
fe-ui这个前端组件库怎么404了？

### ISSUE THREAD

**Issue by lbs123** [WeBankFinTech/fes.js#127]
之前组件地址:https://webankfintech.github.io/fes.js/ui/tooltip.html#%E4%BB%A3%E7%A0%81%E7%A4%BA%E4%BE%8B,现在404，也找不到入口在哪，最近更新之后，出现的问题

**Comment by wanchun** [comment]
https://fesjs.mumblefe.cn/1.0/ui/
