### ISSUE TITLE
[Bug Report/Feeback]

### ISSUE THREAD

**Issue by kinbod** [WeBankFinTech/fes.js#134]
**问题描述**
export default {
    proxy: {
        '/v2': {
            target: 'https://api.douban.com/',
            changeOrigin: true,
        },
    },
};

配置了代理之后，使用：
import { request } from '@fesjs/fes';

request('/api/login', {
    username: 'robby',
    password: '123456',
})
    .then((res) => {
        // do something
    })
    .catch((err) => {
        // 处理异常
    });
代理不起作用

**环境描述/版本信息 (请完成如下信息)**
 - OS: [e.g. Mac/Windows]
 - Node
 - fes -V 2.0.0
 - 项目package.json

**如何复现**
复现步骤
1.
2.
3.
4.

**预期结果**
简明扼要的说明你期待的结果

**截图**
如果可以的话，附上截图

**其它补充内容**
任何和这个问题有关的额外内容

**Comment by wanchun** [comment]
```
proxy: {
  '/v2': {
      target: 'https://api.douban.com/',
      changeOrigin: true,
  },
}
```
表示/v2开头的请求才走代理
