### ISSUE TITLE
时间控件input 最小宽度问题

### ISSUE THREAD

**Issue by canbaoSama** [WeBankFinTech/fes.js#136]
**问题描述**
在外层宽度未固定时，时间控件的input还是会存在最小宽度导致input元素撑出

**环境描述/版本信息 (请完成如下信息)**
 - OS: Windows
 - chrome
 - Node
 - @fesjs/fes: 2.0.19
 - @fesjs/fes-design: 0.5.14

**如何复现**
复现步骤
1. 在form表单中添加时间控件， type="daterange"

**预期结果**
input添加width: 100%

**截图**
![image](https://user-images.githubusercontent.com/29093170/177243753-53695619-9a5a-4efc-998b-1d405dd97c4b.png)

**其它补充内容**
任何和这个问题有关的额外内容

**Comment by winixt** [comment]
fixed in @fesjs/fes-design@0.5.15
