### ISSUE TITLE
初始页面403

### ISSUE THREAD

**Issue by kinbod** [WeBankFinTech/fes.js#138]
**问题描述**
简明扼要的描述你的问题

3.0.0-beta版本，模板app启动后直接到403页面

**环境描述/版本信息 (请完成如下信息)**
 - OS: [e.g. Mac/Windows]
 - Node
 - fes -V 
 - @fesjs/create-fes-app@3.0.0-beta.6
 - 项目package.json
 - {
  "name": "@fesjs/template",
  "version": "3.0.0-beta.0",
  "description": "fes项目模版",
  "scripts": {
    "build": "fes build",
    "prod": "FES_ENV=prod fes build",
    "analyze": "ANALYZE=1 fes build",
    "dev": "fes dev",
    "test:unit": "fes test:unit"
  },
  "keywords": [
    "管理端",
    "fes",
    "fast",
    "easy",
    "strong"
  ],
  "files": [
    ".eslintrc.js",
    ".gitignore",
    ".fes.js",
    ".fes.prod.js",
    "mock.js",
    "package.json",
    "README.md",
    "tsconfig.json",
    "/src",
    "/config"
  ],
  "repository": {
    "type": "git",
    "url": "git+https://github.com/WeBankFinTech/fes.js.git",
    "directory": "packages/fes-template"
  },
  "author": "harrywan",
  "license": "MIT",
  "bugs": {
    "url": "https://github.com/WeBankFinTech/fes.js/issues"
  },
  "homepage": "https://github.com/WeBankFinTech/fes.js#readme",
  "publishConfig": {
    "access": "public"
  },
  "devDependencies": {
    "@vue/compiler-sfc": "^3.2.6",
    "@webank/eslint-config-webank": "^1.0.2"
  },
  "dependencies": {
    "@fesjs/builder-vite": "^3.0.0-beta.1",
    "@fesjs/fes": "^3.0.0-beta.0",
    "@fesjs/fes-design": "^0.5.0",
    "@fesjs/plugin-access": "^3.0.0-beta.0",
    "@fesjs/plugin-enums": "^3.0.0-beta.0",
    "@fesjs/plugin-layout": "^5.0.0-beta.0",
    "@fesjs/plugin-model": "^3.0.0-beta.4",
    "@fesjs/plugin-pinia": "^3.0.0-beta.4",
    "@fesjs/plugin-request": "^3.0.0-beta.7",
    "core-js": "^3.19.2",
    "pinia": "^2.0.14",
    "vue": "^3.2.6"
  },
  "private": true
}

**如何复现**
复现步骤
1. yarn dev
2.访问8000端口
3.
4.

**预期结果**
简明扼要的说明你期待的结果
访问到首页

**截图**
如果可以的话，附上截图

export const beforeRender = {
    loading: <PageLoading />,
    action() {
        const { setRole } = access;
        return new Promise((resolve) => {
            setTimeout(() => {
                setRole('admin');
                // 初始化应用的全局状态，可以通过 useModel('@@initialState') 获取，具体用法看@/components/UserCenter 文件
                resolve({
                    userName: '李雷',
                });
            }, 1000);
        });
    },
};

应该是这块的 setRole比较滞后

**其它补充内容**
任何和这个问题有关的额外内容

**Comment by wanchun** [comment]
已知问题，使用最新版3.0.0-beta.8
