### ISSUE TITLE
FesApi.fetch 的时候碰到 Server-end API error 错误

### ISSUE THREAD

**Issue by textproofreading** [WeBankFinTech/fes.js#14]
调用api时候发生错误：
经过测试：

>     1） 调用服务器 api 接口 /api/v1/search/cms/keywords/add ， 可以正常访问
>     2） fetch 时，提交的 data {} 数据，后台可以正常获得
>     3） 服务器 api response json数据 ： {"status":"you are logged in"} ，状态正常

调用代码：
    

> this.FesApi.fetch('/api/v1/search/cms/keywords/add',{username:'a@163.com',password:'pass'}).then((res) => {
>                 console.log("query_search res:", res);                
>     });

问题描述：
在 FireFox web console 中发现错误信息，如下：

```
    Uncaught (in promise) Error: Server-end API error, please contact the admin.
        success index.js:141
        promise callback*action index.js:235
        fetch index.js:288
        search index.vue:94
        VueJS 4
        handleClick fes-ui.js:8265
        VueJS 33
    index.js:141
```

预期结果：在 console 打印： 
    console.log("query_search res:", res);     

Server-end API error 这个错误信息不知道怎么调试，但是不知道那里出现了错误。

补充，如果把上面代码 then 中的 ： (res) 替换成 ： res ，如下：

> this.FesApi.fetch('/api/v1/search/cms/keywords/add',{username:'a@163.com',password:'pass'}).then(   res => {
>                 console.log("query_search res:", res);                
>     });

**仍然会报错**，但是错误 不在 Web console 中出现，而是以： popup message 的方式显示：

**Server-end API error, please contact the admin.**

多谢
​

**Comment by wanchun** [comment]
出现提示接口错误的原因：
FesApi默认的响应接口如下：
```
this.FesApi.setResponse({
     successCode : "0",
     codePath : "code",
     messagePath : "msg",
     resultPath : "result"  
});
```
而这次请求的响应内容为{"status":"you are logged in"} 。

FesApi解析到的业务码为undefined，不等于设置的业务成功状态码“0”，判断本次请求为失败，而且未找到错误消息，就提示了默认错误信息。

接口请求的状态分为两种：
1、http状态码  
2、业务状态码
只有http状态码为2xx和业务状态码为`successCode`时，接口调用才表示为成功。

例如创建用户请求：
如果校验用户账号不符合要求，这时候可以定义错误码“-1”，返回错误消息“用户名不符合规范”。
```
{ code: "-1", msg: "账号不符合规范", result: {   } }
```

业务码是比较通用的做法~

**Comment by textproofreading** [comment]
@wanchun 

多谢说明，已经调试通过了。
