### ISSUE TITLE
[Bug Report/Feeback]

### ISSUE THREAD

**Issue by ximenpo** [WeBankFinTech/fes.js#17]
**问题描述**
使用 yarn 安装fes_cli 后，初始化完的项目无法正常运行

**环境描述/版本信息 (请完成如下信息)**
 - OS: Mac
 - Browser chrome, safari
 - Node 14
 - fes 0.1.0

**如何复现**
复现步骤
1. yarn global add @webank/fes-cli
2. fes init f1 && cd f1
3. npm I
4. npm run dev

会出现报错信息，大意是找不到某些node_modules下的库

**预期结果**
简明扼要的说明你期待的结果

**截图**

**其它补充内容**
使用NPM 安装的fes_cli 初始化的项目是可以正常运行的

**Comment by winixt** [comment]
fix in v0.2.0
