### ISSUE TITLE
[Feature request/新需求]路由的meta信息动态修改

### ISSUE THREAD

**Issue by auaa** [WeBankFinTech/fes.js#173]
**您的Feature Request/想法是否与已有问题有关? 请描述。**

我希望可以动态设置路由的属性。
此需求可用在多页签的时候，动态路由上。

如果多页签，路由的title都是一样的，客户不容易知道需要点击的内容。

**Comment by wanchun** [comment]
@fesjs/plugin-layout@5.0.0-rc.7，提供了useTabTitle，具体看文档或者 `next` 分支 `fes-template`

**Comment by auaa** [comment]
已解决
