### ISSUE TITLE
按照官网生成新项目,会报loader版本不对,重新升级也不行....向往能直接安装使用相同版本

### ISSUE THREAD

**Issue by wlll122** [WeBankFinTech/fes.js#18]
ERROR in ./node_modules/@webank/fes-core/src/views/layout/root.vue
Module Error (from C:/Users/ll/AppData/Roaming/npm/node_modules/@webank/fes-cli/node_modules/vue-loader/lib/index.js):

Vue packages version mismatch:

- vue@2.6.11 (C:\Users\ll\AppData\Roaming\npm\node_modules\vue\dist\vue.runtime.common.js)
- vue-template-compiler@2.6.12 (C:\Users\ll\AppData\Roaming\npm\node_modules\@webank\fes-cli\node_modules\vue-template-compiler\package.json)

This may cause things to work incorrectly. Make sure to use the same version for both.
If you are using vue-loader@>=10.0, simply update vue-template-compiler.
If you are using vue-loader@<10.0 or vueify, re-installing vue-loader/vueify should bump vue-template-compiler to the latest.

**Comment by winixt** [comment]
删除 node_modules和package-lock.json，再重新 npm i 一下。

还不行的话，麻烦提供下 npm、node 版本，谢谢

**Comment by wlll122** [comment]
> 删除node_modules和package-lock.json，再重新npm i一下。
> 
> 还不行的话，麻烦提供下npm，node版本，谢谢

还是不行,npm 6.14.7  nodev12.18.2
