### ISSUE TITLE
[Bug Report] list demo 项目，console 中提示错误信息

### ISSUE THREAD

**Issue by textproofreading** [WeBankFinTech/fes.js#19]
**问题描述**
简明扼要的描述你的问题

 执行 fes init [project] 之后，点击菜单：列表
 在 console 控制台上看到如下信息：

vue.esm.js?a026:628 [Vue warn]: Invalid prop: type check failed for prop "value". Expected Date, Array, Number, got String with value "".

found in

---> <Calendars> at /Users/harrywan/company/git/fes.js/packages/fes-ui/src/components/date-picker/calendars.vue
       <PickerPopup> at /Users/harrywan/company/git/fes.js/packages/fes-ui/src/components/v-picker-popup/pickerPopup.vue
         <InputDatePicker> at /Users/harrywan/company/git/fes.js/packages/fes-ui/src/components/date-picker/datePicker.vue
           <FormItem> at /Users/harrywan/company/git/fes.js/packages/fes-ui/src/components/form/formItem.vue
             <WbForm> at /Users/harrywan/company/git/fes.js/packages/fes-ui/src/components/form/form.vue
               <Modal> at /Users/harrywan/company/git/fes.js/packages/fes-ui/src/components/modal/modal.vue
                 <Index> at src/pages/list/index.vue
                   <Root>

**环境描述/版本信息 (请完成如下信息)**
 - OS: [e.g. Mac/Windows]
     Ubuntu
     Chrome
 - Node
    v10.19.0
 - fes -V
      0.20
 - 项目package.json

**如何复现**
复现步骤
1. fes init [project]
2.  登录后，点击左侧的列表 /list 
3.  在 browser 的 console 中出现上述 错误信息 （UI显示正常）
4.  点击其他几个菜单没有上述 console 错误

**预期结果**
简明扼要的说明你期待的结果

去掉上述错误报错内容。

**Comment by wanchun** [comment]
fixed
