### ISSUE TITLE
使用 vite 构建配置 viteHtml 报错

### ISSUE THREAD

**Issue by 94ashui** [WeBankFinTech/fes.js#196]
**Describe the bug**
使用 vite 构建配置 viteHtml 报错

**To Reproduce**
<img width="416" alt="image" src="https://github.com/WeBankFinTech/fes.js/assets/89236888/5ec99f6d-c8a5-4c6a-a763-910c1fb1d9a8">

<img width="349" alt="image" src="https://github.com/WeBankFinTech/fes.js/assets/89236888/db13b235-c13f-4797-bd72-c602673e9d9a">

**Expected behavior**
viteHtml 配置正常生效

**Comment by wanchun** [comment]
给下package.json信息

**Comment by 94ashui** [comment]
> 给下package.json信息

`
{
    "name": "@fesjs/template",
    "version": "3.0.0",
    "description": "fes项目模版",
    "scripts": {
        "dev": "FES_ENV=dev fes dev",
        "build": "FES_ENV=prod fes build",
        "analyze": "ANALYZE=1 fes build",
        "test:unit": "fes test:unit"
    },
    "publishConfig": {
        "access": "public"
    },
    "devDependencies": {
        "@fesjs/builder-vite": "^3.0.1",
        "@rushstack/eslint-patch": "^1.3.1",
        "@tsconfig/node16": "^1.0.4",
        "@types/node": "^20.2.5",
        "@vue/eslint-config-prettier": "^7.1.0",
        "@vue/eslint-config-typescript": "^11.0.3",
        "@vue/tsconfig": "^0.4.0",
        "eslint": "^8.42.0",
        "eslint-plugin-vue": "^9.14.1",
    },
    "dependencies": {
        "@fesjs/fes": "^3.1.1",
        "@fesjs/plugin-access": "^3.1.0",
        "@fesjs/plugin-enums": "^3.0.0",
        "@fesjs/plugin-icon": "^3.0.0",
        "@fesjs/plugin-model": "^3.0.0",
        "@fesjs/plugin-pinia": "^3.0.0",
        "core-js": "^3.30.2",
        "lodash-es": "^4.17.21",
        "pinia": "^2.1.3",
        "vue": "^3.3.4"
    },
    "private": true
}

`
