### ISSUE TITLE
搞一个admin或者antd pro那样的集成后台

### ISSUE THREAD

**Issue by chennqqi** [WeBankFinTech/fes.js#2]
建议搞一个admin或者antd pro那样的集成后台，更容易火

**Comment by wanchun** [comment]
其实道理都懂，奈何最最缺的就是UI资源，正在想法办搞来Ui资源

**Comment by wanchun** [comment]
> 建议搞一个admin或者antd pro那样的集成后台，更容易火

道理都懂，奈何最最缺的就是UI资源，正在想法办搞来UI资源。除了模板这些，fes.js也有可取的地方，有兴趣试用一下。

**Comment by pengliheng** [comment]
直接切换 element-UI

**Comment by chennqqi** [comment]
> 直接切换 element-UI

element-UI已经凉凉了
