### ISSUE TITLE
[Bug Report/Feeback]

### ISSUE THREAD

**Issue by qbob** [WeBankFinTech/fes.js#21]
**问题描述**

UI组件Pagination 分页 样式错误

**环境描述/版本信息 (请完成如下信息)**
 - OS: Mac
 - Browser: Chrome

**截图**
![image](https://user-images.githubusercontent.com/1908445/94253389-d80a1b00-ff57-11ea-8565-4cc885c1c0b8.png)

**Comment by wanchun** [comment]
> **问题描述**
> 
> UI组件Pagination 分页 样式错误
> 
> **环境描述/版本信息 (请完成如下信息)**
> 
> * OS: Mac
> * Browser: Chrome
> 
> **截图**
> ![image](https://user-images.githubusercontent.com/1908445/94253389-d80a1b00-ff57-11ea-8565-4cc885c1c0b8.png)

hi，截图看不见，不知道样式错误是什么，可以使用图床 https://sm.ms/
