### ISSUE TITLE
pnpm dev报错

### ISSUE THREAD

**Issue by wdzyy** [WeBankFinTech/fes.js#214]
**问题描述**
简明扼要的描述你的问题
运行项目报错

**环境描述/版本信息 (请完成如下信息)**
 - OS: [e.g. Mac/Windows]   windows
 - Browser [e.g. chrome, safari]  chrome
 - Node 16.17.1
 - fes -V "version": "3.0.0",
 - 项目package.json
![image](https://github.com/WeBankFinTech/fes.js/assets/22287693/c4f92ac2-3cc7-4b60-901a-648c28d529b4)

**如何复现**
复现步骤
1.  安装完依赖 pnpm i
2. pnpm dev时报错，报错如下图
3.
4.

**预期结果**
简明扼要的说明你期待的结果

**截图**
如果可以的话，附上截图
![image](https://github.com/WeBankFinTech/fes.js/assets/22287693/888d7005-7762-4924-8122-8f5bc9a9fc82)

**其它补充内容**
任何和这个问题有关的额外内容

**Comment by yyuyang** [comment]
我也有报错，通过控制台报错，貌似是某项依赖出了问题
![image](https://github.com/WeBankFinTech/fes.js/assets/27001771/64b7e560-9db7-49c1-889b-1404bae5d720)
同样是初始化以后启动报错

**Comment by winixt** [comment]
@wdzyy 看下 npmrc 的配置，如果用 pnpm 需要在 `.npmrc` 加

```
shamefully-hoist=true
```

**Comment by wanchun** [comment]
打开 https://github.com/WeBankFinTech/fes.js/tree/master/packages/create-fes-app/templates/app/pc，然后copy下[.npmrc](https://github.com/WeBankFinTech/fes.js/blob/master/packages/create-fes-app/templates/app/pc/.npmrc) 到你的项目根目录，再重新执行pnpm i
