### ISSUE TITLE
[Bug Report/Feeback]

### ISSUE THREAD

**Issue by PettyHandSome** [WeBankFinTech/fes.js#22]
**问题描述**
FesApi设置Response无效

**环境描述/版本信息 (请完成如下信息)**
 - OS: [Windows]
 - Browser [chrome]
 - Node
 - fes  0.2.3
 - 项目package.json
{
  "name": "@webank/fes-template",
  "version": "0.2.3",
  "description": "fes项目模版",
  "main": "index.js",
  "scripts": {
    "build": "fes build",
    "dev": "fes dev" 
  },
  "keywords": [
    "管理端",
    "fes",
    "fast",
    "easy",
    "strong"
  ],
  "files": [
    ".eslintrc.js",
    ".gitignore",
    "fes.config.js",
    "mock.js",
    "package.json",
    "README.md",
    "/src"
  ],
  "repository": {
    "type": "git"
  },
  "author": "harrywan qlin",
  "license": "MIT",
  "devDependencies": {
    "@webank/eslint-config-webank": "^0.1.4",
    "csp-html-webpack-plugin": "^4.0.0"
  },
  "dependencies": {
    "@antv/data-set": "^0.11.7",
    "@antv/g2": "^4.0.15",
    "@babel/runtime-corejs3": "^7.11.2",
    "@webank/fes-cli": "^0.2.3",
    "@webank/fes-core": "^0.2.3",
    "@webank/fes-ui": "^0.2.3",
    "qs": "^6.9.4"
  },
  "gitHead": "65337782e4c87fae9450be6ad0080038d939f235"
}

**如何复现**
复现步骤
1.在aap.js中设置一下内容
    this.FesApi.option({
        transformRequest: [function (data) {
          return qs.stringify(data)
        }]
    });

    // 设置响应结构
    this.FesApi.setResponse({
        resultPath : '*' 
    });
    
    this.FesApi.setHeader({
        'Content-Type': 'application/x-www-form-urlencoded'
   })
2.任意界面调用如下接口
let datas = {'Code':'admin', 'Password': '123456'}
            this.FesApi.fetch('/Authorization/Login',datas).then(res=>{
                console.log(res)
            })

**预期结果**
请求接口返回内容正常

**截图**
如果可以的话，附上截图
![image](https://user-images.githubusercontent.com/16127328/94382275-ae770c80-016e-11eb-9f8b-1a5b0c0bf0d6.png)

![image](https://user-images.githubusercontent.com/16127328/94382289-b9ca3800-016e-11eb-825b-52333de2887b.png)

**其它补充内容**
任何和这个问题有关的额外内容

**Comment by wanchun** [comment]
初步观察是接口未返回任何响应，还没到FesApi解析

**Comment by PettyHandSome** [comment]
![image](https://user-images.githubusercontent.com/16127328/94383808-a2da1480-0173-11eb-9911-5e582fc12c9a.png)

**Comment by wanchun** [comment]
问题解决没？
