### ISSUE TITLE
webpack配置不灵活，无法使用unplugin-auto-import/webpack等插件

### ISSUE THREAD

**Issue by huanghaiyang** [WeBankFinTech/fes.js#236]
在使用element-plus时希望组件按需加载，文档参考https://element-plus.org/zh-CN/guide/quickstart.html

其中插件unplugin-auto-import/webpack无法使用，或不知道如何使用

**Comment by huanghaiyang** [comment]
`const AutoImport = require('unplugin-auto-import/webpack');
const Components = require('unplugin-vue-components/webpack');
const { ElementPlusResolver } = require('unplugin-vue-components/resolvers');

chainWebpack(config, { env, webpack }) {
        config.plugin('AutoImport').use(
            AutoImport.default({
                resolvers: [ElementPlusResolver()],
            }),
        );
        config.plugin('Components').use(
            Components.default({
                resolvers: [ElementPlusResolver()],
            }),
        );
    },
`

**Comment by huanghaiyang** [comment]
resolved

**Comment by winixt** [comment]
不建议使用，假设某天不想用了，会很头大，特别是项目大的时候
