### ISSUE TITLE
[Feature request] alias 支持?

### ISSUE THREAD

**Issue by pengliheng** [WeBankFinTech/fes.js#28]
**您的Feature Request/想法是否与已有问题有关? 请描述。**
简明扼要的描述你的需求、想法、建议

好像不支持 alias, 也没看到有哪里可以配置它.

https://webpack.js.org/configuration/resolve/#resolvealias

**简述你想要的解决方案**
没有可以不填写
无.

**描述你考虑过的替代方案**
是否有替代方案、你看过的不错的参考方案、交互方案等

**其它补充内容**
任何和这个问题有关的额外内容

**Comment by winixt** [comment]
可以简单描述下你的需求场景吗？

**Comment by pengliheng** [comment]
好吧, 我已经通过 `webpack.config.js` 配置出来了,
