### ISSUE TITLE
安装fes-cli，init了项目后，运行报错缺少fes-code模块

### ISSUE THREAD

**Issue by lianghuilin** [WeBankFinTech/fes.js#3]
错误代码如下：

 ERROR  Failed to compile with 1 errors                                      4:15:07 ├F10: PM┤
This dependency was not found:

* E:\code\skywares-admin\node_modules\@webank\fes-core\src\app.js in multi webpack-hot-middleware/client?reload=true C:/Users/Admin/AppData/Roaming/npm/node_modules/@webank/fes-cli/node_modules/babel-polyfill ./node_modules/@webank/fes-core/src/app.js

To install it, you can run: npm install --save E:\code\skywares-admin\node_modules\@webank\fes-core\src\app.js
webpack built 158881a6b07d7f5de2cf in 12851ms
× ｢wdm｣: Hash: 158881a6b07d7f5de2cf
Version: webpack 4.44.1
Time: 12851ms
Built at: 2020-09-02 4:15:07 ├F10: PM┤
     Asset      Size  Chunks             Chunk Names
index.html  1.35 KiB          [emitted]
 js/app.js   1.5 MiB     app  [emitted]  app
Entrypoint app = js/app.js
[0] multi webpack-hot-middleware/client?reload=true C:/Users/Admin/AppData/Roaming/npm/node_modules/@webank/fes-cli/node_modules/babel-polyfill ./node_modules/@webank/fes-core/src/app.js 52 bytes {app} [built]
[C:\Users\Admin\AppData\Roaming\npm\node_modules\@webank\fes-cli\node_modules\ansi-html\index.js] C:/Users/Admin/AppData/Roaming/npm/node_modules/@webank/fes-cli/node_modules/ansi-html/index.js 4.64 KiB {app} [built]
[C:\Users\Admin\AppData\Roaming\npm\node_modules\@webank\fes-cli\node_modules\ansi-regex\index.js] C:/Users/Admin/AppData/Roaming/npm/node_modules/@webank/fes-cli/node_modules/ansi-regex/index.js 136 bytes {app} [built]
[C:\Users\Admin\AppData\Roaming\npm\node_modules\@webank\fes-cli\node_modules\babel-polyfill\lib\index.js] C:/Users/Admin/AppData/Roaming/npm/node_modules/@webank/fes-cli/node_modules/babel-polyfill/lib/index.js 833 bytes {app} [built]
[C:\Users\Admin\AppData\Roaming\npm\node_modules\@webank\fes-cli\node_modules\babel-polyfill\node_modules\regenerator-runtime\runtime.js] C:/Users/Admin/AppData/Roaming/npm/node_modules/@webank/fes-cli/node_modules/babel-polyfill/node_modules/regenerator-runtime/runtime.js 24.2 KiB {app} [built]
[C:\Users\Admin\AppData\Roaming\npm\node_modules\@webank\fes-cli\node_modules\core-js\fn\regexp\escape.js] C:/Users/Admin/AppData/Roaming/npm/node_modules/@webank/fes-cli/node_modules/core-js/fn/regexp/escape.js 108 bytes {app} [built]
[C:\Users\Admin\AppData\Roaming\npm\node_modules\@webank\fes-cli\node_modules\core-js\modules\_core.js] C:/Users/Admin/AppData/Roaming/npm/node_modules/@webank/fes-cli/node_modules/core-js/modules/_core.js 124 bytes {app} [built]
[C:\Users\Admin\AppData\Roaming\npm\node_modules\@webank\fes-cli\node_modules\core-js\shim.js] C:/Users/Admin/AppData/Roaming/npm/node_modules/@webank/fes-cli/node_modules/core-js/shim.js
8.22 KiB {app} [built]
[C:\Users\Admin\AppData\Roaming\npm\node_modules\@webank\fes-cli\node_modules\querystring-es3\index.js] C:/Users/Admin/AppData/Roaming/npm/node_modules/@webank/fes-cli/node_modules/querystring-es3/index.js 126 bytes {app} [built]
[C:\Users\Admin\AppData\Roaming\npm\node_modules\@webank\fes-cli\node_modules\strip-ansi\index.js] C:/Users/Admin/AppData/Roaming/npm/node_modules/@webank/fes-cli/node_modules/strip-ansi/index.js 162 bytes {app} [built]
[C:\Users\Admin\AppData\Roaming\npm\node_modules\@webank\fes-cli\node_modules\webpack-hot-middleware\client-overlay.js] (webpack)-hot-middleware/client-overlay.js 2.14 KiB {app} [built]
[C:\Users\Admin\AppData\Roaming\npm\node_modules\@webank\fes-cli\node_modules\webpack-hot-middleware\client.js?reload=true] (webpack)-hot-middleware/client.js?reload=true 7.58 KiB {app} [built]
[C:\Users\Admin\AppData\Roaming\npm\node_modules\@webank\fes-cli\node_modules\webpack-hot-middleware\process-update.js] (webpack)-hot-middleware/process-update.js 4.25 KiB {app} [built]
[C:\Users\Admin\AppData\Roaming\npm\node_modules\@webank\fes-cli\node_modules\webpack\buildin\global.js] (webpack)/buildin/global.js 905 bytes {app} [built]
[C:\Users\Admin\AppData\Roaming\npm\node_modules\@webank\fes-cli\node_modules\webpack\buildin\module.js] (webpack)/buildin/module.js 552 bytes {app} [built]
    + 332 hidden modules

ERROR in multi webpack-hot-middleware/client?reload=true C:/Users/Admin/AppData/Roaming/npm/node_modules/@webank/fes-cli/node_modules/babel-polyfill ./node_modules/@webank/fes-core/src/app.js
Module not found: Error: Can't resolve 'E:\code\skywares-admin\node_modules\@webank\fes-core\src\app.js' in 'E:\code\skywares-admin'
 @ multi webpack-hot-middleware/client?reload=true C:/Users/Admin/AppData/Roaming/npm/node_modules/@webank/fes-cli/node_modules/babel-polyfill ./node_modules/@webank/fes-core/src/app.js app[2]

ERROR in   Error: Child compilation failed:
  Entry module not found: Error: Can't resolve 'E:\code\skywares-admin\node_modules\@webank\fe  s-core\src\index.html' in 'E:\code\skywares-admin':
  Error: Can't resolve 'E:\code\skywares-admin\node_modules\@webank\fes-core\src\index.html' i  n 'E:\code\skywares-admin'
  
  - compiler.js:79 
    [npm]/[fes-cli]/[html-webpack-plugin]/lib/compiler.js:79:16
  
  - Compiler.js:343 
    [npm]/[fes-cli]/[webpack]/lib/Compiler.js:343:11
  
  - Compiler.js:681 
    [npm]/[fes-cli]/[webpack]/lib/Compiler.js:681:15
  
  
  - Hook.js:154 AsyncSeriesHook.lazyCompileHook
    [npm]/[fes-cli]/[tapable]/lib/Hook.js:154:20
  
  - Compiler.js:678 
    [npm]/[fes-cli]/[webpack]/lib/Compiler.js:678:31
  
  
  - Hook.js:154 AsyncSeriesHook.lazyCompileHook
    [npm]/[fes-cli]/[tapable]/lib/Hook.js:154:20
  
  - Compilation.js:1423 
    [npm]/[fes-cli]/[webpack]/lib/Compilation.js:1423:35
  
  
  - Hook.js:154 AsyncSeriesHook.lazyCompileHook
    [npm]/[fes-cli]/[tapable]/lib/Hook.js:154:20
  
  - Compilation.js:1414 
    [npm]/[fes-cli]/[webpack]/lib/Compilation.js:1414:32
  
  
  - Hook.js:154 AsyncSeriesHook.lazyCompileHook
    [npm]/[fes-cli]/[tapable]/lib/Hook.js:154:20
  
  - Compilation.js:1409 
    [npm]/[fes-cli]/[webpack]/lib/Compilation.js:1409:36
  
  

Child html-webpack-plugin for "index.html":

    ERROR in Entry module not found: Error: Can't resolve 'E:\code\skywares-admin\node_modules\@webank\fes-core\src\index.html' in 'E:\code\skywares-admin'
i ｢wdm｣: Failed to compile.
GET /favicon.ico 500 7.516 ms - 2421
[SUCCESS] mock.js 加载成功
TypeError: res.json is not a function
    at C:\Users\Admin\AppData\Roaming\npm\node_modules\@webank\fes-cli\build\mock\init.js:102:21
    at Layer.handle [as handle_request] (C:\Users\Admin\AppData\Roaming\npm\node_modules\@webank\fes-cli\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Users\Admin\AppData\Roaming\npm\node_modules\@webank\fes-cli\node_modules\express\lib\router\index.js:317:13)
    at C:\Users\Admin\AppData\Roaming\npm\node_modules\@webank\fes-cli\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (C:\Users\Admin\AppData\Roaming\npm\node_modules\@webank\fes-cli\node_modules\express\lib\router\index.js:335:12)
    at next (C:\Users\Admin\AppData\Roaming\npm\node_modules\@webank\fes-cli\node_modules\express\lib\router\index.js:275:10)
    at C:\Users\Admin\AppData\Roaming\npm\node_modules\@webank\fes-cli\node_modules\express\lib\router\index.js:635:15
    at next (C:\Users\Admin\AppData\Roaming\npm\node_modules\@webank\fes-cli\node_modules\express\lib\router\index.js:260:14)
    at Function.handle (C:\Users\Admin\AppData\Roaming\npm\node_modules\@webank\fes-cli\node_modules\express\lib\router\index.js:174:3)
    at router (C:\Users\Admin\AppData\Roaming\npm\node_modules\@webank\fes-cli\node_modules\express\lib\router\index.js:47:12)
    at C:\Users\Admin\AppData\Roaming\npm\node_modules\@webank\fes-cli\build\mock\init.js:88:20
    at Layer.handle [as handle_request] (C:\Users\Admin\AppData\Roaming\npm\node_modules\@webank\fes-cli\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Users\Admin\AppData\Roaming\npm\node_modules\@webank\fes-cli\node_modules\express\lib\router\index.js:317:13)
    at C:\Users\Admin\AppData\Roaming\npm\node_modules\@webank\fes-cli\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (C:\Users\Admin\AppData\Roaming\npm\node_modules\@webank\fes-cli\node_modules\express\lib\router\index.js:335:12)
    at next (C:\Users\Admin\AppData\Roaming\npm\node_modules\@webank\fes-cli\node_modules\express\lib\router\index.js:275:10)

**Comment by winixt** [comment]
请问 node 和系统版本是多少？

init 初始化项目的时候有什么报错吗？看Error提示是 fes-core 依赖包没装上，麻烦在当前项目目录下执行：

npm i 

然后再试下，看看还有无问题
