### ISSUE TITLE
二级访问路径怎么配置？谢谢！

### ISSUE THREAD

**Issue by 4593645** [WeBankFinTech/fes.js#33]
例如，安装好内网，公网只能映射http://域名/fes 到具体的机器上面。请问如何实现，麻烦，祝君愉快！

**Comment by wanchun** [comment]
> 例如，安装好内网，公网只能映射[http://域名/fes](http://%E5%9F%9F%E5%90%8D/fes) 到具体的机器上面。请问如何实现，麻烦，祝君愉快！

这是部署的问题，应该从服务器部署静态资源着手解决问题，比如nginx可以映射某个ip+端口+path到指定目录，同时把build生成的静态资源文件copy到此目录。

**Comment by 4593645** [comment]
> > 例如，安装好内网，公网只能映射[http://域名/fes](http://%E5%9F%9F%E5%90%8D/fes) 到具体的机器上面。请问如何实现，麻烦，祝君愉快！
> 
> 这是部署的问题，应该从服务器部署静态资源着手解决问题，比如nginx可以映射某个ip+端口+path到指定目录，同时把build生成的静态资源文件copy到此目录。

java或者相关的项目都可以快速解经域路径端口等访问问题，为何npm的项目就这样繁琐？好项目应该是能够提供良好的配置解经路径问题，而不依赖第三方nginx或者apache或lighttpd。谢谢。

**Comment by wanchun** [comment]
> > > 例如，安装好内网，公网只能映射[http://域名/fes](http://%E5%9F%9F%E5%90%8D/fes) 到具体的机器上面。请问如何实现，麻烦，祝君愉快！
> > 
> > 
> > 这是部署的问题，应该从服务器部署静态资源着手解决问题，比如nginx可以映射某个ip+端口+path到指定目录，同时把build生成的静态资源文件copy到此目录。
> 
> java或者相关的项目都可以快速解经域路径端口等访问问题，为何npm的项目就这样繁琐？好项目应该是能够提供良好的配置解经路径问题，而不依赖第三方nginx或者apache或lighttpd。谢谢。

咋说呢，fes.js是纯前端领域的东西，负责从开发到构建流程，不管理如何部署，部署在哪。node生态中的一些项目，比如express有你想要的东西。
