### ISSUE TITLE
不搞个 demo 页体验一下吗？

### ISSUE THREAD

**Issue by chenzesam** [WeBankFinTech/fes.js#4]

**Comment by wanchun** [comment]
> _No description provided._
you can create a project, like this:
```shell
fes init my-project 
cd my-project
fes dev
```

**Comment by chenzesam** [comment]
> > _No description provided._
> > you can create a project, like this:
> 
> ```shell
> fes init my-project 
> cd my-project
> fes dev
> ```

我说类似 antd-pro 的在线 demo，让人最快的感官体验一下。

**Comment by wanchun** [comment]
有道理，页面模板做好后弄一个在线demo，谢谢老哥

**Comment by winixt** [comment]
http://webank.gitee.io/fes-pro/#/home 可以访问这个地址体验下

**Comment by zhan-ge** [comment]
> http://webank.gitee.io/fes-pro/#/home 可以访问这个地址体验下

请问这个 demo 的代码有开源吗，希望学习参考一下
