### ISSUE TITLE
以fes文件后缀的文件的在编辑器中打开没有代码样式，阅读起来很难，有什么好的办法吗

### ISSUE THREAD

**Issue by lixintong** [WeBankFinTech/fes.js#43]
以fes文件后缀的文件的在编辑器中打开没有代码样式，阅读起来很难，有什么好的办法吗

**简述你想要的解决方案**
没有可以不填写

**描述你考虑过的替代方案**
是否有替代方案、你看过的不错的参考方案、交互方案等

**其它补充内容**
任何和这个问题有关的额外内容

**Comment by wanchun** [comment]
> 以fes文件后缀的文件的在编辑器中打开没有代码样式，阅读起来很难，有什么好的办法吗
> 
> **简述你想要的解决方案**
> 没有可以不填写
> 
> **描述你考虑过的替代方案**
> 是否有替代方案、你看过的不错的参考方案、交互方案等
> 
> **其它补充内容**
> 任何和这个问题有关的额外内容

有两种办法：
1. 直接使用.vue后缀
2. 或者配置vscode：
```
"files.associations": {
      "*.html": "html"
}
 ```
