### ISSUE TITLE
[Feature request/新需求]

### ISSUE THREAD

**Issue by CasualMing** [WeBankFinTech/fes.js#45]
**您的Feature Request/想法是否与已有问题有关? 请描述。**
简明扼要的描述你的需求、想法、建议

按照楼主提供的体验地址，简单的体验了一下，发现菜单切换特别的僵硬，太突兀了，希望切换的时候，可以加个简单的动画

**简述你想要的解决方案**
没有可以不填写

在menu组件外使用<transtions> 过渡动画实现过渡，不至于切换太过生硬

**描述你考虑过的替代方案**
是否有替代方案、你看过的不错的参考方案、交互方案等

**其它补充内容**
任何和这个问题有关的额外内容

建议动画可以增加参数配置，例如衔接的快慢之类的

**Comment by wanchun** [comment]
> **您的Feature Request/想法是否与已有问题有关? 请描述。**
> 简明扼要的描述你的需求、想法、建议
> 
> 按照楼主提供的体验地址，简单的体验了一下，发现菜单切换特别的僵硬，太突兀了，希望切换的时候，可以加个简单的动画
> 
> **简述你想要的解决方案**
> 没有可以不填写
> 
> 在menu组件外使用 过渡动画实现过渡，不至于切换太过生硬
> 
> **描述你考虑过的替代方案**
> 是否有替代方案、你看过的不错的参考方案、交互方案等
> 
> **其它补充内容**
> 任何和这个问题有关的额外内容
> 
> 建议动画可以增加参数配置，例如衔接的快慢之类的

体验地址是1.0的代码，在Vue3分支使用最新的@fesjs/plugin-layout插件，切换是有动画的，体验好一些。建议查看最新的文档，参考上手体验一下。
