### ISSUE TITLE
[Feature request/新需求]求支持 SSR

### ISSUE THREAD

**Issue by ycjcl868** [WeBankFinTech/fes.js#46]
**您的Feature Request/想法是否与已有问题有关? 请描述。**
简明扼要的描述你的需求、想法、建议

**简述你想要的解决方案**
没有可以不填写

**描述你考虑过的替代方案**
是否有替代方案、你看过的不错的参考方案、交互方案等

**其它补充内容**
任何和这个问题有关的额外内容

**Comment by wanchun** [comment]
有兴趣自己实现吗，我们这边提供帮助

**Comment by ycjcl868** [comment]
> 有兴趣自己实现吗，我们这边提供帮助

没兴趣
