### ISSUE TITLE
建议table的column可以直接通过数据配置，而不是繁琐的模板

### ISSUE THREAD

**Issue by xlzy520** [WeBankFinTech/fes.js#5]

**Comment by wanchun** [comment]
当初设计时，有过这种想法。最终还是觉得模板的方式更语义化一些，其实模板也可以v-for快速生成的呀，模板可以支持高级模板，比如展开更多等。但是用数据配置的话，需要手动去关联插槽。其实就是模板更语义化一点，用v-for快速生成模板也不是很繁琐。或者兴趣来创建一个高阶组件，传配置？

**Comment by xlzy520** [comment]
@wanchun 之前用element的时候，也是弄了高阶组件，传配置。插槽的话，普通的组件直接传类型，自定义的组件，可以传component，或者render jsx。手动v-for的话，还需要处理很多东西，比如选择框、插槽处理，等等。
