### ISSUE TITLE
安装时遇错：文件名、目录名或卷标语法不正确

### ISSUE THREAD

**Issue by ModeSpr** [WeBankFinTech/fes.js#50]
**问题描述**
安装时遇错，安装成功，创建未成功

> 文件名、目录名或卷标语法不正确。
> error Command failed.
> Exit code: 1
> Command: D:\nodejs\node_global\bin\create-fes-app
> Arguments: vue-fesjs

**环境描述/版本信息 (请完成如下信息)**
 - OS: Windows
 - Browser：edge
 - Node：14.15.3
 - fes -V1.22.10

**如何复现**
复现步骤
1.PS D:\DATA\Documents\GitHub> yarn create @fesjs/fes-app vue-fesjs

**预期结果**
安装成功，创建成功

**截图**
如果可以的话，附上截图

**其它补充内容**
任何和这个问题有关的额外内容

**Comment by wanchun** [comment]
给下错误截图，目前的描述不够明确

**Comment by ModeSpr** [comment]
![20210414233351717](https://user-images.githubusercontent.com/53519168/114738336-73d76900-9d7a-11eb-8b89-bb86c5012bb8.png)

**Comment by ModeSpr** [comment]
最近有学习umijs遇到了相同的问题，网上找到了解决方案，原来是yarn的bin和dir放在了不同的硬盘分区。
https://www.cnblogs.com/cailijuan/p/13685912.html

**Comment by ModeSpr** [comment]
最近有学习umijs遇到了相同的问题，网上找到了解决方案，原来是yarn的bin和dir放在了不同的硬盘分区。

**Comment by wanchun** [comment]
好的，那我关了哈
