### ISSUE TITLE
组件是直接用antd-vue的组件吗 还是fes-ui

### ISSUE THREAD

**Issue by ripeBoy** [WeBankFinTech/fes.js#53]
**您的Feature Request/想法是否与已有问题有关? 请描述。**
简明扼要的描述你的需求、想法、建议

**简述你想要的解决方案**
没有可以不填写

**描述你考虑过的替代方案**
是否有替代方案、你看过的不错的参考方案、交互方案等

**其它补充内容**
任何和这个问题有关的额外内容

**Comment by wanchun** [comment]
Vue3版本的组件库还在升级改造中，可以用antdv

**Comment by ripeBoy** [comment]
> Vue3版本的组件库还在升级改造中，可以用antdv

好的，感谢，还想请教一个问题，就是fes里面的packages可以单独引用到我目前的项目里吗？比如request

**Comment by wanchun** [comment]
> > Vue3版本的组件库还在升级改造中，可以用antdv
> 
> 好的，感谢，还想请教一个问题，就是fes里面的packages可以单独引用到我目前的项目里吗？比如request

去看下request的文档，虽然没懂你的意思，但是插件都是可以按需使用的

**Comment by ripeBoy** [comment]
> > > Vue3版本的组件库还在升级改造中，可以用antdv
> > 
> > 
> > 好的，感谢，还想请教一个问题，就是fes里面的packages可以单独引用到我目前的项目里吗？比如request
> 
> 去看下request的文档，虽然没懂你的意思，但是插件都是可以按需使用的

我的意思就是fes-plugin-request这个包可以脱离fes生态使用吗？比如在我目前用vue-cli创建的项目中

**Comment by ripeBoy** [comment]
有人可以回答一下我这个问题吗？fes-plugin-request这个包可以脱离fes生态使用吗？比如在我目前用vue-cli创建的项目中

**Comment by wanchun** [comment]
> 有人可以回答一下我这个问题吗？fes-plugin-request这个包可以脱离fes生态使用吗？比如在我目前用vue-cli创建的项目中

不行，推荐用fes.js哈，Vue-cli的项目转过来也简单。
