### ISSUE TITLE
[Bug Report/Feeback]

### ISSUE THREAD

**Issue by wangguangyin1123** [WeBankFinTech/fes.js#54]
**问题描述**
简明扼要的描述你的问题
使用this.FesApi.Fetch调接口时，如果`resultPath`对应字段传过来的是false或者0，会拿不到相应数据。源码中做的判断是返回一个空对象
![image](https://user-images.githubusercontent.com/13529916/115537645-9fec7000-a2cd-11eb-8d96-4cc4d19243a7.png)

**环境描述/版本信息 (请完成如下信息)**
 - OS: [e.g. Mac/Windows]
 - Node
 - fes -V
 - 项目package.json

**如何复现**
复现步骤
1.
2.
3.
4.

**预期结果**
简明扼要的说明你期待的结果

**截图**
如果可以的话，附上截图

**其它补充内容**
任何和这个问题有关的额外内容

**Comment by wanchun** [comment]
晚点修复

**Comment by wanchun** [comment]
已修复，请更新至@webank/fes-core@0.4.6
