### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by image72** [WeBankFinTech/fes.js#6]
能把 组件 Fes-xxx,内置方法之类的全小写吗？
一直切换大小写 痛苦指数++

本来就是fes-cli 搭建的项目，其中各个属性还附带上fes 略显繁琐，重复命名
```
<Wb-button v-permission:="/hr/shelf-action"></Wb-button>
 this.FesApp.setAllowPage(['/hr/shelf-action', ...])
FesData,
FesSyncData,
FesEnv
#FesStorage
#FesUtil
#FesApi
#FesLeft
#FesHeader
#FesData

```

**Comment by wanchun** [comment]
> 能把 组件 Fes-xxx,内置方法之类的全小写吗？
> 一直切换大小写 痛苦指数++
> 
> 本来就是fes-cli 搭建的项目，其中各个属性还附带上fes 略显繁琐，重复命名
> 
> ```
> <Wb-button v-permission:="/hr/shelf-action"></Wb-button>
>  this.FesApp.setAllowPage(['/hr/shelf-action', ...])
> FesData,
> FesSyncData,
> FesEnv
> #FesStorage
> #FesUtil
> #FesApi
> #FesLeft
> #FesHeader
> #FesData
> ```

的确有，有计划重新整理API命名，多谢建议
