### ISSUE TITLE
mock.js文件里加上proxy代理 项目启动报错

### ISSUE THREAD

**Issue by toStorying** [WeBankFinTech/fes.js#73]
**问题描述**
简明扼要的描述你的问题
如题 在mock.js文件里加上 cgiMock.proxy('http://192.168.10.221:8090/qualitis')之后 项目启动报错

**环境描述/版本信息 (请完成如下信息)**
 - OS: MAC 
 - Browser chrome
 - Node:v14.17.4
 - fes -V: 执行fes -v提示没有安装fes
 
 - 项目package.json:
 - {
  "name": "Exchangis",
  "version": "0.5.0",
  "description": "Exchangis",
  "main": "app.js",
  "scripts": {
    "build": "fes build",
    "serve": "fes dev",
    "fix": "eslint --ext .fes src --fix"
  },
  "keywords": [
    "管理端",
    "fes",
    "fast",
    "easy",
    "strong"
  ],
  "files": [
    ".eslintrc.js",
    ".gitignore",
    "fes.config.js",
    "mock.js",
    "package.json",
    "README.md",
    "/src"
  ],
  "repository": {
    "type": "git"
  },
  "author": "harrywan qlin",
  "license": "MIT",
  "devDependencies": {
    "@vue/test-utils": "^1.1.0",
    "@webank/eslint-config-webank": "^0.1.4",
    "@webank/fes-cli": "^0.4.6",
    "chai": "^4.2.0",
    "csp-html-webpack-plugin": "^4.0.0"
  },
  "dependencies": {
    "@webank/fes-core": "^0.4.8",
    "@webank/fes-ui": "^0.4.8",
    "chart.js": "^2.9.4",
    "vue-chartjs": "^3.5.1"
  },
  "gitHead": "357575247bde6d1d24a8d2e11d2bfe7adbe6abd6"
}

**如何复现**
mock.js配置如图
![image](https://user-images.githubusercontent.com/33798721/136510970-4e3ba3f6-3061-4c75-8871-478bed2e14fe.png)

报错信息如图:
![image](https://user-images.githubusercontent.com/33798721/136511078-c4a08728-ef25-4612-aa8f-11b0391c79e1.png)

**Comment by Aysnine** [comment]
仍然有问题，在 `@webank/fes-cli@0.4.8`。

错误的原因是 fes-cli 的 `createMock.js`，里面的 148 行有一个多余的事件监听，和 122 行中的操作是重复的，这是作者的低级错误：

https://github.com/WeBankFinTech/fes.js/blob/2927915a6ca9c9db99570239c6684643d83d60d8/packages/fes-cli/build/helpers/createMock.js#L114-L160

如果你也不幸被坑在这个版本，又不方便升级，可以临时修改项目本地的这个文件 `node_modules/@webank/fes-cli/build/helpers/createMock.js`，将 148-150 注释掉：

``` js
        // proxy.on('proxyReq', (proxyReq) => {
        //     proxyReq.setHeader('Host', url.parse(host).host);
        // });
```

祝你好运
