### ISSUE TITLE
安装fes.js失败

### ISSUE THREAD

**Issue by Su1024** [WeBankFinTech/fes.js#92]
**问题描述**
简明扼要的描述你的问题
安装fes.js失败

**环境描述/版本信息 (请完成如下信息)**
 - OS: [e.g. Mac/Windows]
 - Node  16.13.1
 - fes -V
 - 项目package.json

**如何复现**
复现步骤
1. 使用 npm install @webank/fes-cli -g 命令安装
2.提示失败
3.
4.
![image](https://user-images.githubusercontent.com/23012179/149706756-2bb12d8b-386f-463f-8ddd-ce1737ad6eb2.png)

**预期结果**
简明扼要的说明你期待的结果

**截图**
如果可以的话，附上截图

![image](https://user-images.githubusercontent.com/23012179/149706758-cd815a7c-eb96-4990-80c3-cf6a8df5d3a1.png)

**其它补充内容**
任何和这个问题有关的额外内容

**Comment by wanchun** [comment]
1.0 版本需要 node 10，16太高了
