### ISSUE TITLE
侧边栏收起时会被多选框覆盖[Bug Report]

### ISSUE THREAD

**Issue by zwj13513118235** [WeBankFinTech/fes.js#93]
**Describe the bug**

**To Reproduce**
1. 创建一个具有多选框的表格
2. 点击收起侧边栏
3. 手表移入侧边栏使侧边栏弹出

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/71361115/150484657-e8caa670-e4dd-4e05-925d-51a6b49bf725.png)

**Desktop (please complete the following information):**
 - OS:  iOS
 - Browser chrome
 - Version 0.2.5

**Additional context**

**Comment by wanchun** [comment]
升级到 @fesjs/fes-design@0.2.6
