### ISSUE TITLE
[Feature request/新需求]

### ISSUE THREAD

**Issue by JamesBonddu** [WeBankFinTech/fes.js#94]
请在Fes.js 1.0 支持vueRouter路由切换history模式

**Comment by wanchun** [comment]
history模式下，如果刷新则会404，需要开发时devServer和发布后的承载服务器对对路由做特殊处，非根路由的请求需要映射到根路由，所以不是必要情况下，实际上是不方便的。你们是有什么场景需要histroy模式吗，能说明下吗？或者考虑下使用 Vue3 版本，已支持。
